### ISSUE TITLE
link-local addresses alongside routable interfaces

### ISSUE THREAD

**Issue by hgomersall** [keepsimple1/mdns-sd#121]
This looks like it might be relevant to #119 . In our system we wish to be able to resolve devices on a link local subnet whilst still having routable interfaces active. The comment in the code suggest clients might have a problem, but it's not clear what that problem is.

Is there some way (including through modifying the library) to enable link-local mdns-sd whilst still having routable interfaces?

**Comment by keepsimple1** [comment]
By `link local subnet`, did you mean `169.254.0.0/16` subnet?

**Comment by hgomersall** [comment]
> By `link local subnet`, did you mean `169.254.0.0/16` subnet?

Yes exactly. One of the interfaces acquired a link local address so is excluded from browsing.

**Comment by hgomersall** [comment]
Yes, I can confirm that 0.7.3 works just fine. The previous work around was to disable the interfaces that weren't link-local as noted from code introduced in #117.

**Comment by keepsimple1** [comment]
Thanks for confirming. I've reverted the change in #117 and posted a new release 0.7.5.  Also yanked 0.7.4 just in case.

**Comment by keepsimple1** [comment]
Fixed released. If any problem, please re-open this issue, or report a new one. Thanks!
