### ISSUE TITLE
Trouble with query_missing_srv()

### ISSUE THREAD

**Issue by lyager** [keepsimple1/mdns-sd#156]
I've experienced some trouble in the latest release with the above function, and just wondering if additional querying of SRV entries are within spec? 

What happens is that the SRV query within the function above is very aggressive, and if a SRV never comes it will spam the network.

There should probably be a stopping mechanism if no answer hits the cache?

**Comment by keepsimple1** [comment]
I've opened a PR to solve this issue. If possible, please let me know if the patch would work for you. Thanks!

**Comment by lyager** [comment]
Sorry for the rather short reporting. I think querying for SRV is fine. But your observation is correct, it might not be fruitful to do so when it's not within the TY that we're browsing for.

Also, what if the device that fails to initially send a SRV response never does? 

I wont be able to properly test the PR this year, due to being out of office, but I'm pretty sure that the PR is a good shot, and what is expected of the package.

**Comment by keepsimple1** [comment]
> Sorry for the rather short reporting. I think querying for SRV is fine. But your observation is correct, it might not be fruitful to do so when it's not within the TY that we're browsing for.

no problem. 

> 
> Also, what if the device that fails to initially send a SRV response never does?

With the PR, we will stop querying for SRV after two attempts, and the service instance will not be resolved.

> 
> I wont be able to properly test the PR this year, due to being out of office, but I'm pretty sure that the PR is a good shot, and what is expected of the package.

Thanks for reviewing the PR.  No problem, I will also try to add a test case.

**Comment by keepsimple1** [comment]
refactored the patch and did manual tests.  Merged the patch. Take it for a spin when you have time in new year ;-)
