### ISSUE TITLE
Updating service info when service is registered

### ISSUE THREAD

**Issue by richardhozak** [keepsimple1/mdns-sd#161]
Hello, is there a way to update ServiceInfo of a registered service, for example hostname or some txt record that would get re-announces to listening clients without unregistering and registering the service again? Also how expensive is doing unregistration and registration again with changed info, is there a way to do this efficiently?

**Comment by keepsimple1** [comment]
You should be able to re-announce by registering with the new info. No need to unregister first. Let me know if that helps. (I don't have time to test it myself at the moment. )

**Comment by richardhozak** [comment]
Thank you, it works perfectly.
