### ISSUE TITLE
When a receiver is dropped, the error produced by sender should not be Error

### ISSUE THREAD

**Issue by irvingoujAtDevolution** [keepsimple1/mdns-sd#173]
It is very possible that mDNS scan is being done in an async manner with timeout, when a future that containing the receiver is dropped when timed out, we naturely wants to stop brose using the stopBrowse method to clean up resources.

**Comment by keepsimple1** [comment]
This library does not use async, can you please elaborate the details? And what do you mean by `the receiver` and `sender` here?

**Comment by irvingoujAtDevolution** [comment]
`the receiver`  refers to the flume receiver when browsing a new service
```
let receiver = service_daemon.browse(service_name.as_ref()).with_context(|| {
            let err_msg = format!("failed to browse for service: {}", service_name);
            error!(error = err_msg);
            err_msg
})?;
```

The sender of course, refers to the sender on the other side of the channel.

Flume supports async send and with the receiver interface 
```
impl<T> Receiver<T> {
    /// Asynchronously receive a value from the channel, returning an error if all senders have been
    /// dropped. If the channel is empty, the returned future will yield to the async runtime.
    pub fn recv_async(&self) -> RecvFut<'_, T> { <<-------------- This is returns a future
        RecvFut::new(OwnedOrRef::Ref(self))
    }

   //....
}
```

**Comment by keepsimple1** [comment]
I see. The error refers to [this one](https://github.com/keepsimple1/mdns-sd/blob/4d719a3a47152b634a0314bfd9041690772b6e29/src/service_daemon.rs#L648), right? 

I assume that in your code it is not easy, or doesn't make much sense to read `SearchStopped` event, right? As you already are in the process of drop after a time out.

As this is not critical error, we could reduce the logging level of this one to WARN or INFO.  Is `WARN` okay or no?

**Comment by irvingoujAtDevolution** [comment]
Yes! INFO is preferred on my side, but for the sake of the project, I think `WARN` might be the better choice. At whichever you prefer

**Comment by keepsimple1** [comment]
Fix merged. Let me know if any problems.
