### ISSUE TITLE
add Windows support

### ISSUE THREAD

**Issue by keepsimple1** [keepsimple1/mdns-sd#18]
NOTE: if you are familiar with socket support on Windows in Rust, please feel free to comment on this issue. 

I started to find cases when I wanted to use this library on Windows. Don't know how to implement yet. This is a placeholder to this new feature.

Update: after some research I plan to use `winapi` crate to add support on Windows. Hopefully there are not too many gotcha.

**Comment by keepsimple1** [comment]
@indietyp @lu-zero  I wonder if any of you are interested in Windows support of this lib?  If yes, what do you think of the approach I tried in the linked PR?

**Comment by lu-zero** [comment]
I do not use windows, so I cannot say much sadly :/

**Comment by indietyp** [comment]
I have a windows machine (which I do not use primarily for development), so I'd be happy to take a look.

**Comment by keepsimple1** [comment]
The PR is merged now.
