### ISSUE TITLE
Too verbose logging, even when logging is not enabled

### ISSUE THREAD

**Issue by acfsmith** [keepsimple1/mdns-sd#197]
First of all, thanks for the great library!  I have tried a lot of DNS resolver libraries for Rust and this one works best for me.

Only problem is excessive logging.  I use it without logging enabled: `mdns-sd = { version = "0.10.5", features = ["async"] }`. But still I have tons of debug messages in the logs.

**Comment by keepsimple1** [comment]
Thanks! 

> Only problem is excessive logging. I use it without logging enabled: mdns-sd = { version = "0.10.5", features = ["async"] }. But still I have tons of debug messages in the logs.

You would need to add `default-features = false`, like this: 

`mdns-sd = { version = "0.10.5", default-features = false, features = ["async"] }`

**Comment by keepsimple1** [comment]
I think I answered your question. Please feel free to re-open this issue if you have more questions.

**Comment by acfsmith** [comment]
Sorry for the long answer.  If default-features = false, the project won't compile because it still tries to use logs.

**Comment by keepsimple1** [comment]
> Sorry for the long answer. If default-features = false, the project won't compile because it still tries to use logs.

You are right, good catch! I created a PR #212 to fix this.  Thanks a lot!

**Comment by keepsimple1** [comment]
I've merged the fix.  Let me know if it works for you.

**Comment by keepsimple1** [comment]
If any problems, please let me know. Thanks!
