### ISSUE TITLE
allow multiple addresses in ServiceInfo

### ISSUE THREAD

**Issue by indietyp** [keepsimple1/mdns-sd#20]
The `ServiceInfo` struct can hold multiple corresponding addresses, but there is no way to add more than a single addr (only one via `ServiceInfo::new`). Would it be possible to add the ability to define multiple addresses?

**Comment by keepsimple1** [comment]
Since `host_ipv4` is `&str` in `ServiceInfo::new`,  we could add support specifying one or more ipv4 addresses in the same string, separated by `,` or some other separator.  What do you think?  (any other suggestions are welcome).

**Comment by indietyp** [comment]
Going with a string separated by `,` would be a good idea, but also adding methods like `insert_address` and `remove_address` for a more programmatic approach.

One could also imagine having an optional dependency on the [ipnet](https://crates.io/crates/ipnet) crate, which provides access to an [`Ipv4AddrRange`](https://docs.rs/ipnet/2.5.0/ipnet/struct.Ipv4AddrRange.html) and [`Ipv4Net`](https://docs.rs/ipnet/2.5.0/ipnet/struct.Ipv4Net.html) struct.

I'd be happy to create a pull request that implements those changes.

**Comment by keepsimple1** [comment]
Adding methods like `insert_address` and `remove_address` sounds good to me.  I'm reluctant to add a new dependency for this purpose, unless something really useful.

Thank you for submitting the PR. Will take a look.

**Comment by indietyp** [comment]
#21 was merged, closing this issue
