### ISSUE TITLE
project reorganisation

### ISSUE THREAD

**Issue by indietyp** [keepsimple1/mdns-sd#22]
This is the tracking issue for project reorganization. Instead of having a giant `lib.rs` file, split the file into multiple files that are smaller to make maintenance and adding new features more accessible.

**Comment by keepsimple1** [comment]
As mentioned in https://github.com/keepsimple1/mdns-sd/pull/21/files#r870534842 ,  I will try to do this after the linked PR.

**Comment by keepsimple1** [comment]
I plan to work on this after the Release 0.5.3.

**Comment by keepsimple1** [comment]
Divide this work into several small steps:

- [ ] separate out `ServiceInfo` and `Error`, `Result`.

**Comment by keepsimple1** [comment]
Reopen as we still have other steps to complete.

**Comment by indietyp** [comment]
Great work!

**Comment by keepsimple1** [comment]
Done. Closing this issue.
