### ISSUE TITLE
panicked at 'range end index 2 out of range for slice of length 1', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.10.5/src/dns_parser.rs:1144:38

### ISSUE THREAD

**Issue by rise0chen** [keepsimple1/mdns-sd#233]
panicked at 'range end index 2 out of range for slice of length 1', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.10.5/src/dns_parser.rs:1144:38

**Comment by keepsimple1** [comment]
Thanks for opening this issue. I've opened a PR to catch such error. If that works, I will add similar checks for some other internal functions as well.

**Comment by keepsimple1** [comment]
I've merged in the patch. If there are any problems, please feel free to re-open this issue or create a new one.
