### ISSUE TITLE
Feature request: send ServiceRemoved() for expired service types when browsing `_services._dns-sd._udp.local.`

### ISSUE THREAD

**Issue by hrzlgnm** [keepsimple1/mdns-sd#246]
Those PTR records usually have a TTL of 4500 by default. I have a special use case where I would like to get notified when those expire and are not refreshed anymore. 

I'm also happy to implement this myself if there is an interest having that feature. My coarse idea is to check whether we have browsers for the ty_domain `_services._dns-sd._udp.local.` And notify ServiceRemoved when PTR records of those expire.

**Comment by hrzlgnm** [comment]
I guess that feature is kind of working already, i just missed it when trying to figure out whether this works already:

I get the following when i turn on and off a linux machine that is the some machine publishing _ssh and _sftp-ssh:
```
At 737.7812153s: ServiceFound("_services._dns-sd._udp.local.", "_ssh._tcp.local.")
At 737.7813342s: ServiceFound("_services._dns-sd._udp.local.", "_sftp-ssh._tcp.local.")
At 751.9583198s: ServiceRemoved("_services._dns-sd._udp.local.", "_sftp-ssh._tcp.local.")
At 751.9584203s: ServiceRemoved("_services._dns-sd._udp.local.", "_ssh._tcp.local.")
```

What i didn't got yet, when that machine is just unpugged from the network or the VM is just suspended, but that's a rather long debug session to run for 1.25h wait time, but I'm trying now.

**Comment by hrzlgnm** [comment]
I did some more tests, and also ran the cargo test while having the query example running for a longer time

I guess my requested feature already works like expected:

```
At 27.5909725s: ServiceFound("_services._dns-sd._udp.local.", "_known-answer._udp.local.")
At 27.5918703s: ServiceFound("_services._dns-sd._udp.local.", "_my-service2._udp.local.")
...
At 4095.0333551s: SearchStarted()
At 4527.594399s: ServiceRemoved("_services._dns-sd._udp.local.", "_known-answer._udp.local.")
At 4527.5964958s: ServiceRemoved("_services._dns-sd._udp.local.", "_my-service2._udp.local.")
```
After 4500s the service type that expires is notified using ServiceRemoved already.

And my anticipated `_ssh._tcp` and `_sft-ssh._tcp` service types:
```
At 1050.9879295s: ServiceFound("_services._dns-sd._udp.local.", "_ssh._tcp.local.")
At 1050.9880522s: ServiceFound("_services._dns-sd._udp.local.", "_sftp-ssh._tcp.local.")
...
At 5554.1528907s: ServiceRemoved("_services._dns-sd._udp.local.", "_ssh._tcp.local.")
At 5554.1530081s: ServiceRemoved("_services._dns-sd._udp.local.", "_sftp-ssh._tcp.local.")
```
So I'm closing this issue, sorry for the any inconveniences :)

**Comment by keepsimple1** [comment]
In a related note, if you wanted to go further to get `ServiceRemoved` as soon as possible, there is an open issue: https://github.com/keepsimple1/mdns-sd/issues/54 .  I have an idea in mind to add a `verify()` API to support such use case, but didn't get all ironed out yet. If you would like to have that issue resolved / or have the `verify` API, let me know by commenting on that issue. I think more real world use case will help drive resolving that one.
