### ISSUE TITLE
panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.11.3/src/dns_parser.rs:1465:26: range end index 9002 out of range for slice of length 8972

### ISSUE THREAD

**Issue by rise0chen** [keepsimple1/mdns-sd#249]
panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/mdns-sd-0.11.3/src/dns_parser.rs:1465:26: range end index 9002 out of range for slice of length 8972

**Comment by keepsimple1** [comment]
Thanks for opening this issue! I've created a patch to fix this. If you could verify the fix, that will be great!

**Comment by rise0chen** [comment]
I create a PR https://github.com/keepsimple1/mdns-sd/pull/251

We can test some random data

**Comment by keepsimple1** [comment]
Thanks! PRs merged. I kind of made a mess of the commit history as it's the first time I merge PR into a feature branch and then into the main ;-)
