### ISSUE TITLE
Disallow resolving certain domains

### ISSUE THREAD

**Issue by AMythicDev** [keepsimple1/mdns-sd#278]
I have been using the ServiceDaemon to both publish and search a service, basically something like a peer to peer network. However one issue that I encounter is that the ServiceDaemon also resolves addresses that belongs to itself, which is basically pointless.

Although this may not seem much of a problem, but a solution to this problem can also be potentially extended to cases where we want to blacklist resolving certain hosts.

**Comment by keepsimple1** [comment]
>  However one issue that I encounter is that the ServiceDaemon also resolves addresses that belongs to itself, which is basically pointless.

When this happens, did you publish the service on the local host as well? If yes, it's expected to resolve the addresses that belong to the local host.  If not, or if you think otherwise, could you please elaborate the details ?

**Comment by AMythicDev** [comment]
> did you publish the service on the local host as well?
Yes the publisher and querier live on the same device

**Comment by keepsimple1** [comment]
> I wanted to know if this is possible to ignore resolving certain addresses such as the local host without first resolving them.
> 
> Although reading the RFC 6763 more thoroughly I see it might not be possible. Still I am keeping this open for your comments.

To me, it doesn't make sense to "ignore resolving certain addresses" in general. Like you probably noticed, it would not be compliant to RFC if `ServiceDaemon` does not resolve all instances and addresses available.

That said, for the specific case of resolving local addresses, we could try to disable `IP_MULTICAST_LOOP` via socket option. I've never used this option before, so will do some experiments.

**Comment by AMythicDev** [comment]
> To me, it doesn't make sense to "ignore resolving certain addresses" in general. Like you probably noticed, it would not be compliant to RFC if ServiceDaemon does not resolve all instances and addresses available.

Yeah I got that.

> That said, for the specific case of resolving local addresses, we could try to disable IP_MULTICAST_LOOP via socket option. I've never used this option before, so will do some experiments.

Cool do let me know if you got any successes with that.

Anyways thanks for the response. I am closing this now.

**Comment by keepsimple1** [comment]
@AMythicDev I got a chance to try out `IP_MULTICAST_LOOP` option. From a simple test case, it seems working.  Could you please try it out to see if it works for you?  (even though this issue was closed).
