### ISSUE TITLE
Multiple Streams using AioQuic

### ISSUE THREAD

**Issue by Karthikdasari0423** [keepsimple1/mdns-sd#29]
hai ,

It is not an issue.
one small quick query

@keepsimple1 
Could you please confirm were you able to create multiple streams in a single connection using the AIOQUIC code you have in Github.

Sorry for raising an issue as i am unable to find your email to ask this query.

Looking forward for your reply

Thank you.

**Comment by keepsimple1** [comment]
@Karthikdasari0423  not worries. I've not used Python aioquic for a while, so cannot confirm on top of my mind.  My email is:  keepsimple@gmail.com . You can send me email and I will follow up there. Thanks. 

I will close this issue for now.
