### ISSUE TITLE
Multiple IP addresses don't work correctly over network

### ISSUE THREAD

**Issue by oscartbeaumont** [keepsimple1/mdns-sd#41]
When exposing an MDNS service with multiple ip addresses this library does not seem to work correctly. If the same machine is used for both discovery and advertising the service, all ips show up correct but if the advertisement goes across the network between two machines (I am testing with a Mac and Linux machine), only one IP address will show up when the service is discovered on the remote device.

[Code I am using](https://gist.github.com/oscartbeaumont/0a069836041e257b5649f26b7b028ba7)

**Comment by keepsimple1** [comment]
Thank you for opening this issue.  This seems to be a bug, where the daemon resolves the instances after receiving the 1st IP address.  We should resolve the instance after handling all answers in the incoming message.

I've opened a PR to fix this issue. My local test shows it fixed the problem. Could you please try out the PR branch and let me know if it works for you? Thanks.

**Comment by oscartbeaumont** [comment]
That PR seems to have fixed it on my end. Thanks for the super quick response.

**Comment by keepsimple1** [comment]
Thanks for confirming. PR is merged into `main` branch. Will close this issue. If any problems, feel free to open new issues.

**Comment by keepsimple1** [comment]
I plan to finish issue #22 and have a new crates.io release in this weekend.

**Comment by keepsimple1** [comment]
v0.5.4 is published ;)
