### ISSUE TITLE
Join multicast group error: An invalid argument was supplied. (os error 10022)

### ISSUE THREAD

**Issue by fufesou** [keepsimple1/mdns-sd#47]
Log from [mikekgr](https://github.com/mikekgr) in discussion https://github.com/rustdesk/rustdesk/discussions/844#discussioncomment-3111117

OS: Win10
```
IPv4 addrs: [100.125.199.128, 192.168.0.108, 192.168.1.186, 172.29.96.1]
new socket bind to 100.125.199.128:5353
new socket bind to 192.168.0.108:5353
join multicast group on addr 192.168.1.186: An invalid argument was supplied. (os error 10022), 
```

The [code](https://github.com/keepsimple1/mdns-sd/blob/23ed4acb9432efae922eeb6febb328a0c6968f89/src/service_daemon.rs#L527).

I can't reproduce on my PC. I'm not sure if the problem is `100.125.199.128`.
I'll contact him later for more tests.

**Comment by keepsimple1** [comment]
> join multicast group on addr 192.168.1.186: An invalid argument was supplied. (os error 10022), 

It seems that Windows has some special remarks in their [docs](https://docs.microsoft.com/en-us/windows/win32/winsock/multicast-socket-option-behavior): 

> Do not call IP_ADD_MEMBERSHIP with the same group more than once on the same network interface.

But the error code does not match (`WSAEADDRNOTAVAIL` 10049 vs `WSAEINVAL` 10022). And it's not clear what `the same group` means in Windows.  So I'm not sure, just a thought.

**Comment by keepsimple1** [comment]
After the above PR #48 merged, could you please check if this issue still exists?

**Comment by fufesou** [comment]
Ok, I'll contant [mikekgr](https://github.com/mikekgr) for help. Also I'll ask him if his email can be shared to you.

**Comment by keepsimple1** [comment]
I don't think this problem exist any longer. If you found otherwise, please re-open this issue, or create a new issues. Thanks!
