### ISSUE TITLE
Simple browse test return nothing

### ISSUE THREAD

**Issue by jilchab** [keepsimple1/mdns-sd#50]
Hi!

I try to get the IP address of devices connected to my network. When I run in my terminal:
`dns-sd -B _http._tcp` (or just `dns-sd -B`)

I can see my printer but this code below only receive SearchStarted events

```Rust
fn main() {
    let mdns = mdns_sd::ServiceDaemon::new().expect("Failed to create daemon");
    let rcv = mdns.browse("_http._tcp").expect("Failed to browse");

    loop {
        let event = rcv.recv().unwrap();
        println!("event: {:?}", event);
    }
}
```

What did I do wrong?
Thanks

EDIT: I'm on MacOS 12.3.1 | rustc 1.62.1

**Comment by keepsimple1** [comment]
You need to add `.local.` at the end of the service type calling `browse`.  See example at [here](url). Let me know if still not working. I will try to add more doc comments for browse method.

**Comment by jilchab** [comment]
Yes I tried that but I got same event repeatedly `SearchStarted("._http._tcp.local.")`

**Comment by keepsimple1** [comment]
> Yes I tried that but I got the same event repeatedly `SearchStarted("._http._tcp.local.")`

Can you try with no leading `.` as well?  You can also run the `examples/query.rs` of this repo as following to test: (it will append `.local.` for you) 

```
$ cargo run --example query _http._tcp 
    Finished dev [unoptimized + debuginfo] target(s) in 0.04s
     Running `target/debug/examples/query _http._tcp`
Received other event: SearchStarted("_http._tcp.local.")
Received other event: ServiceFound("_http._tcp.local.", "Brother HL-L2390DW._http._tcp.local.")
```

**Comment by jilchab** [comment]
Alright so even without the leading `.` it still not working.
But the example worked fine!

I am still looking what is the difference between my code and the example but it's really weird.

If I found what was wrong I'll let you know.

Thank you!
