### ISSUE TITLE
[windows]: mdns-sd fails to operate if there's a VPN virtual network adapter

### ISSUE THREAD

**Issue by anenankhu** [keepsimple1/mdns-sd#52]
mdns-sd(0.5.5) panics with if VPN adapter is present:
```
Failed to resolve agent address: join multicast group on addr 10.84.0.4: The requested address is not valid in its context. (os error 10049)
```

**Comment by keepsimple1** [comment]
Thanks for the opening the issue.  Is this address `10.84.0.4` you wanted to listen on, or is it okay to skip it?  Are they any details about this interface (`ipconfig`) ?

**Comment by anenankhu** [comment]
I'd like to skip it. It's a turned-off virtual network adapter created by a VPN client on windows. 

I think it's this one, because this issue started to occur immediately after I've installed ProtonVPN(actually happened with other VPN software on WIndows too, I've just happened to uninstall it and the problem went away):

```
> ipconfig /all
...
Unknown adapter Local Area Connection:

   Media State . . . . . . . . . . . : Media disconnected
   Connection-specific DNS Suffix  . :
   Description . . . . . . . . . . . : TAP-ProtonVPN Windows Adapter V9
   Physical Address. . . . . . . . . : 00-FF-99-EC-CB-C1
   DHCP Enabled. . . . . . . . . . . : Yes
   Autoconfiguration Enabled . . . . : Yes
```

**Comment by keepsimple1** [comment]
I'm not familiar with this VPN interface, but I suspect it didn't support multicast. I opened a PR to handle such errors more gracefully. If you can try out the PR branch and see if it works for you, that will be great.

**Comment by anenankhu** [comment]
@keepsimple1 I've tried the PR, it fixes the issue. Thanks!

**Comment by keepsimple1** [comment]
A new version published.
