### ISSUE TITLE
Trailing '.' in instance names are incorrectly removed

### ISSUE THREAD

**Issue by dalepsmith** [keepsimple1/mdns-sd#57]
From https://www.rfc-editor.org/rfc/rfc6763#section-4.1.1

The <Instance> portion of the Service Instance Name is a user-
   friendly name consisting of arbitrary Net-Unicode text [[RFC5198](https://www.rfc-editor.org/rfc/rfc5198)].  It
   MUST NOT contain ASCII control characters (byte values 0x00-0x1F and
   0x7F) [[RFC20](https://www.rfc-editor.org/rfc/rfc20)] but otherwise is allowed to contain any characters,
   without restriction, including spaces, uppercase, lowercase,
   punctuation -- **including dots** -- accented characters, non-Roman text,
   and anything else that may be represented using Net-Unicode.

The code uses `trim_end_matches('.')` which would remove the '.' in `somename.` as from `somename.._http._tcp.local.`

**Comment by dalepsmith** [comment]
#56

**Comment by dalepsmith** [comment]
(attempting to add/reference a PR. This is a bit new to me, sorry)

 See PR  #56

**Comment by keepsimple1** [comment]
Thanks for opening the issue and the PR. I've linked the PR.
