### ISSUE TITLE
Ipv6 support

### ISSUE THREAD

**Issue by lu-zero** [keepsimple1/mdns-sd#61]
Might be nice to detail what is missing and what to add first. @keepsimple1 can you edit this issue with a list of tasks?

**Comment by keepsimple1** [comment]
No problem. Here is a list of tasks on my mind for IPv6 support:

- [ ] responder: support register `ServiceInfo` with IPv4 only or IPv6 only, as well as both IPv4 and IPv6 in one register.
- [ ] responder: recv and process queries on IPv6 interfaces if IPv6 address is configured.
- [ ] responder: send response on IPv6 interface if IPv6 address is configured.
- [ ] querier: send query on IPv6 interface if IPv6 address is configured.
- [ ] querier: recv and handle answers on IPv6 interfaces if IPv6 address is configured.
- [ ] Default setting: both IPv4 and IPv6 is enabled (if addr is configured). Provides API to disable IPv6 (or IPv4). i.e. allow the `ServiceDaemon` to be IPv6 only or IPv4 only.

It is probably easier to test by starting with the responder part, using other existing clients / queriers.
