### ISSUE TITLE
Hostname returned by `ServiceInfo::get_hostname` has a trailing `.`

### ISSUE THREAD

**Issue by WilliamVenner** [keepsimple1/mdns-sd#62]
The hostname returned by `ServiceInfo::get_hostname` appears to always contain a trailing `.`

**Comment by keepsimple1** [comment]
This is expected for a full qualified DNS host name, see here: https://www.rfc-editor.org/rfc/rfc6762#section-3 .

**Comment by WilliamVenner** [comment]
Nope no problem! Maybe it would be worth documenting. On my end I can simply pop the hostname.

Side question: how flexible _is_ the hostname? Can you put any Unicode you want in it? At the moment I put the computer's hostname in there, so it could have whatever in it.
