### ISSUE TITLE
Make log dependency optional

### ISSUE THREAD

**Issue by pixsperdavid** [keepsimple1/mdns-sd#63]
If the log crate is being used for logging in a downstream project, messages from mdns-sd can be undesirable. To avoid this, the dependency could be made optional. 

Here's an example on how this works in the rustls crate:
https://github.com/rustls/rustls/blob/86f4695c8c05a8041807a34d691b9bb07b757df0/rustls/src/lib.rs#L302

Happy to open a PR to implement this if acceptable.

**Comment by keepsimple1** [comment]
Sounds like a good improvement. Thanks for opening the issue and the PR.

**Comment by pixsperdavid** [comment]
Implemented in #64
