### ISSUE TITLE
client query

### ISSUE THREAD

**Issue by gngpp** [keepsimple1/mdns-sd#70]
How do clients specify IP addresses to discover services? I want to get a response on some VPN network to return some parameters.

**Comment by keepsimple1** [comment]
Currently there is no way to specify certain IP addresses to discover services. The clients discover services by calling [`ServiceDaemon::browse`](https://docs.rs/mdns-sd/latest/mdns_sd/struct.ServiceDaemon.html#method.browse) and it will send queries on all valid IPv4 interfaces, including VPN network if it's active. 

One thing you could do is to filter the discovery (i.e. browse) results based on IP addresses in `ServiceInfo`.

**Comment by gngpp** [comment]
- mdns-sd register server
<img width="671" alt="image" src="https://user-images.githubusercontent.com/51810656/198779101-4758702b-9043-441e-b863-79bbfbd6bbc3.png">

<img width="924" alt="image" src="https://user-images.githubusercontent.com/51810656/198779318-565e5af5-9910-4794-a737-7b7d1710133d.png">

-  mdns query client
<img width="895" alt="image" src="https://user-images.githubusercontent.com/51810656/198780767-1fd7c87b-3541-495a-ad5e-7aa5ecf5f6ad.png">

> It only seems to listen to services on the localhost network. My VPN is on the 10.66.66.0/24 network segment

**Comment by gngpp** [comment]
> The mdns server receives the reques.
> This seems to be a problem with my VPN Settings.
>  Thank you for your reply!
<img width="794" alt="image" src="https://user-images.githubusercontent.com/51810656/198813572-329b9f7c-c809-4ddc-8ba8-ddca31b5da63.png">

<img width="1298" alt="image" src="https://user-images.githubusercontent.com/51810656/198813580-af3f940d-ae92-4592-a15a-1e956c5e73b5.png">

>

**Comment by keepsimple1** [comment]
I'm not sure if you resolved this issue. From your logs, it seems the client did find and resolve the service in 10.66.66.0 network: 

<img width="808" alt="Screen Shot 2022-10-29 at 9 47 03 AM" src="https://user-images.githubusercontent.com/7699244/198843439-3e1e322a-3ebf-4019-a485-8efbdfe82c2d.png">

**Comment by gngpp** [comment]
WireGuard VPN is a routing protocol and I looked into it and found that it does not support udp service listening. Okay, now we know the problem.
