### ISSUE TITLE
TXT  inconsistencies with RFC6763

### ISSUE THREAD

**Issue by dalepsmith** [keepsimple1/mdns-sd#71]
EDIT (by @keepsimple1): adding check emojis to track the status of the issues. ✅ means an issue has been solved.

(This should probably be several Issues, sorry.)

# Last key ✅
Supposed to use the first appearance key and ignore repeats.
Keys should ignore case.  "foo", "Foo", "FOO" are all the same key.

# Just key ✅
Needs to differentiate between "key=" and "key".  The former has an
empty value, the latter has NO value.  Only way I can think of is to use
`HashMap<String, Option<String>>` instead of `HashMap<String, String>`

Unfortunately, this is an API change.

# Values are bytes ✅
The value can be any string of bytes including "=" and NUL.
Specifically, it is not required to be utf-8.  So the value type
should probably be `[u8]` instead of a `String`

Unfortunately, this is an API change.

# New publish does not have TXT ✅
If start browsing, existing services have TXT record info.
If I publish a service (with avahi-publish-service), the TXT info is missing.
But if I publish BEFORE I start the browse, I do get the TXT info.

# RFC
https://www.rfc-editor.org/rfc/rfc6763#section-6.3

Everything up to the first '=' character is the key (Section 6.4).

Everything after the first '=' character to the end of the string
(including subsequent '=' characters, if any) is the value (Section
6.5).

https://www.rfc-editor.org/rfc/rfc6763#section-6.4
Rules for Keys in DNS-SD Key/Value Pairs

The characters of a key MUST be printable US-ASCII values (0x20-0x7E)
[RFC20], excluding '=' (0x3D).

Spaces in the key are significant, whether leading, trailing, or in
the middle -- so don't include any spaces unless you really intend
that.

Case is ignored when interpreting a key, so "papersize=A4",
"PAPERSIZE=A4", and "Papersize=A4" are all identical.

If there is no '=' in a DNS-SD TXT record string, then it is a
boolean attribute, simply identified as being present, with no value.

A given key SHOULD NOT appear more than once in a TXT record.

If a client receives a TXT record containing the same key more than
once, then the client MUST silently ignore all but the first
occurrence of that attribute.

https://www.rfc-editor.org/rfc/rfc6763#section-6.5
Rules for Values in DNS-SD Key/Value Pairs

If there is an '=' in a DNS-SD TXT record string, then everything
after the first '=' to the end of the string is the value.  The value
can contain any eight-bit values including '='.

The value is opaque binary data.  Often the value for a particular
attribute will be US-ASCII [RFC20] or UTF-8 [RFC3629] text, but it is
legal for a value to be any binary data.

**Comment by dalepsmith** [comment]
Having TXT records be `HashMap<String, String>` is a very nice and logical API.

However, Keys are *not* utf-8, only printable ascii.
And the Values can be *any* sequence of bytes (including '='), again not utf-8.

**Comment by keepsimple1** [comment]
Thanks for the details!  

> New publish does not have TXT
If start browsing, existing services have TXT record info.
If I publish a service (with avahi-publish-service), the TXT info is missing.
But if I publish BEFORE I start the browse, I do get the TXT info.

This is a bug and worth a separate issue. Would you mind open another issue for it?

**Comment by keepsimple1** [comment]
> However, Keys are not utf-8, only printable ascii.

UTF-8 is backward compatible with ascii. So it's fine to represent ascii using utf-8.
 
> And the Values can be any sequence of bytes (including '='), again not utf-8.

I didn't know that, thanks for pointing it out. Before we change, do you have use cases where you do need to support non-UTF-8 values? I'm trying to see benefit/cost ratio.

**Comment by keepsimple1** [comment]
For other key/value rules, I agree we should fix the code using this issue.

**Comment by dalepsmith** [comment]
Yes!  (Please excuse the top-post)

Sent from my iPhone...
Beware of typos!

**Comment by dalepsmith** [comment]
On 11/10/22, keepsimple1 ***@***.***> wrote:
>> However, Keys are not utf-8, only printable ascii.
>
> UTF-8 is backward compatible with ascii. So it's fine to represent ascii
> using utf-8.

As far as receiving, yes this is fine.  However, *publishing* should
verify that the key has only the allowed characters (0x20 - 0x7e,
except for '=').

>> And the Values can be any sequence of bytes (including '='), again not
>> utf-8.
>
> I didn't know that, thanks for pointing it out. Before we change, do you
> have use cases where you do need to support non-UTF-8 values? I'm trying to
> see benefit/cost ratio.

I don't know of any specifically.  Just noticed it while reading the
RFC.  I would imagine *most* values are just text,  But since the spec
allows it, it's probably out there, or will be. Best be prepared to
handle it somehow.  I don't have a good suggestion.  `Vec<u8>` instead
of `String`?  Maybe an enum?

Also, the no-key and empty key cases ("key" and "key=") should be
distinguished somehow. Maybe with an `Option<>` ?

-Dale

**Comment by keepsimple1** [comment]
> As far as receiving, yes this is fine. However, *publishing* should verify that the key has only the allowed characters (0x20 - 0x7e, except for '=').

Good point. I think we can check it in `ServiceInfo::new()`. 

> I don't know of any specifically. Just noticed it while reading the RFC. I would imagine *most* values are just text, But since the spec allows it, it's probably out there, or will be. Best be prepared to handle it somehow. 

Maybe I'm biased, but I think the world is moving towards UTF-8. It is possible that some rare applications use non-UTF-8 in TXT records but I'm willing to postpone this until a concrete case shows up in our context.

(Some other types in Rust ecosystem face / faced the same problem, for example `std::path::Path`. IMO, the history shows that supporting non-UTF-8 things in a mostly UTF-8 environment can be costly for the end users.) 

> Also, the no-key and empty key cases ("key" and "key=") should be distinguished somehow. Maybe with an `Option<>` ?

Yes, that sounds good to me. And maybe we can take this opportunity to define a type X for TXT key/value pairs so that `ServiceInfo::new()` accepts `X` or `Option<X>` instead of the plain `HashMap<String, String>`. Also, maybe we keep the `new()` as is (deprecate it later), and add a new / better constructor for `ServiceInfo`, maybe even using Builder pattern or something?

**Comment by keepsimple1** [comment]
Two of the problems are resolved in their separated issues: 

- Last Key: #76 .
- New publish does not have TXT:  #72 .

**Comment by keepsimple1** [comment]
All issues mentioned above are addressed in [Release 0.7.0](https://github.com/keepsimple1/mdns-sd/releases/tag/v0.7.0). If any problems, please open a new issue. 

Thanks again @dalepsmith for opening this issue and helping solving them. If anything not working properly, please raise them.
