### ISSUE TITLE
Allow non-standard service names longer than 15 bytes

### ISSUE THREAD

**Issue by smith61** [keepsimple1/mdns-sd#94]
I know the DNS-SD spec specifies that the limit for service names is 15 bytes (plus one for leading _), but some organizations have decided to ignore that part of the spec and use service names that are longer than 15 bytes. For example Google has decided that Android TV would use the service name _androidtvremote2 (a total of 17 bytes including the _).

I've tested with removing that specific check in "check_service_name" and did not notice any issue and clients were able to successfully resolve the service.

**Comment by keepsimple1** [comment]
The limit of 15 bytes for the service name is tight. I think the more important limit is the total 255 bytes for the fully qualified service domain name. Let me check around more.

**Comment by smith61** [comment]
Based on my reading of the spec, it does seem to imply that the service name limit is intended to allow for most of the 255 byte limit to go towards the instance and service/parent domain portions of the FQDN. I haven't seen any issues with clients being unable to parse these non-spec compliant FQDNs, but it potentially is possible that some clients do enforce these constraints.

I can see wanting to keep this crate to be as close to correct standards implementing as possible, but it would be nice to have this ability. Maybe hidden behind an "enable_non_standard_service_name_i_know_what_im_doing" call so people have to acknowledge that this may not work with all clients.

**Comment by keepsimple1** [comment]
I checked the current code, we only call `check_service_name` during `register`. I.e. we only impose the 15-char limit when publishing a service, and we do not impose this limit when browsing the services. 

In other words, a client using this lib can currently resolve a service name that is longer than 15 bytes. I did a test and it worked. 

```
$ cargo run --example query _androidtvremote2._udp
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/examples/query _androidtvremote2._udp`
At 144.447µs : Received other event: SearchStarted("_androidtvremote2._udp.local. on addrs [192.168.0.116]")
At 304.511134ms : Received other event: ServiceFound("_androidtvremote2._udp.local.", "pi._androidtvremote2._udp.local.")
At 304.546957ms: Resolved a new service: pi._androidtvremote2._udp.local. IP: {192.168.0.114} TXT properties: TxtProperties { properties: [TxtProperty { key: "path", val: Some([116, 119, 111]) }] }
```

Did you mean you wanted to use this lib to publish a service (i.e. running as a server) with a service name longer than 15 bytes?

**Comment by smith61** [comment]
Yes, my case I need to advertise a service that has a service name longer than 15 bytes and I do not have control over service name.

**Comment by keepsimple1** [comment]
Got it. One possible solution is to allow setting the service name length limit used by a `ServiceDaemon`. It will be a new command option sending to the daemon. By default, the limit is still 15 bytes. An user can opt in and explicitly send the command option to change the limit to a different value (up to 255).  

What do you think?

**Comment by smith61** [comment]
That would work perfectly fine for me. I'm all for keeping the defaults as close to standards compliant as possible.

**Comment by keepsimple1** [comment]
@smith61 I've created a PR (linked above) for this. If you have time, would you please help check if the patch works for you?

**Comment by keepsimple1** [comment]
Fix merged. If any problems, feel free to open a new issue.
